/* eslint-disable import/prefer-default-export */
export const TUNNELBATCHLIST = "TUNNELBATCHLIST";
export const TUNNELBATCH_ADD = "TUNNELBATCH_ADD";
export const STAGETUNNELBATCHLIST = "STAGETUNNELBATCHLIST";
export const TUNNELBATCH_RECORD_ADD = "TUNNELBATCH_RECORD_ADD";
export const INDICATORSLIST = "INDICATORSLIST";
export const RECORDTUNNELBATCHLIST = "RECORDTUNNELBATCHLIST";
export const TUNNELBATCH_COMPLETE_STAGE = "TUNNELBATCH_COMPLETE_STAGE";
export const TUNNELBATCH_START_STAGE = "TUNNELBATCH_START_STAGE";



//存数据
export const SAVE_TUNNEL_NUMBER = "SAVE_TUNNEL_NUMBER";
export const SAVE_TUNNEL_BATCH_ID = "SAVE_TUNNEL_BATCH_ID";
export const SAVE_TUNNEL_BATCHID_AND_STAGEID = "SAVE_TUNNEL_BATCHID_AND_STAGEID"; 
