/* eslint-disable import/prefer-default-export */
export const TUNNELBATCHLIST = "TUNNELBATCHLIST";
export const TUNNELBATCH_ADD = "TUNNELBATCH_ADD";
export const STAGETUNNELBATCHLIST = "STAGETUNNELBATCHLIST";
export const TUNNELBATCH_RECORD_ADD = "TUNNELBATCH_RECORD_ADD";
export const INDICATORSLIST = "INDICATORSLIST";
export const RECORDTUNNELBATCHLIST = "RECORDTUNNELBATCHLIST";
